package com.benbanking.api.enums;

public enum ActivityType {
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    VIEW_BANK_ACCOUNT,
    VIEW_TRANSACTION_HISTORY,
    CHANGE_PASSWORD,
    UPDATE_PERSONAL_INFORMATION,
    OPEN_NEW_BANK_ACCOUNT,
    CLOSE_BANK_ACCOUNT,
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER,
    EXTERNAL_TRANSFER,
    ADMIN_ACCOUNT_STATUS_CHANGE
}
